# Generated by Django 3.1.2 on 2021-09-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(default='', upload_to='pic_img'),
        ),
    ]
